### ISSUE TITLE
+ char becomes a blank space

### ISSUE THREAD

**Issue by criroselli** [ljharb/qs#152]
It's normal this behaviour?
`
var qs = require('qs');
var assert = require('assert');

var obj = qs.parse('a=+c');
assert.deepEqual(obj, { a: ' c' });
`
Why '+c' becomes  ' c' ?
Thanks

**Comment by ljharb** [comment]
This is indeed normal behavior - most web servers do this. If you want a `+`, you'd need it to be URI-encoded - note the result of `qs.stringify({ a: '+c' })`

**Comment by criroselli** [comment]
Ok perfect.
Thank you

**Comment by svincent** [comment]
This issue states that it's a non-issue and tj/node-querystring#106 says it's by design, but I don't quite get why. This behavior seems like an application-level concern. 

As far as I can tell the HTML spec and URI/URL-related RFCs don't specify this behavior. The [Wikipedia article on Query String](https://en.wikipedia.org/wiki/Query_string#URL_encoding) notes that "SPACE is encoded as '+' or '%20'", but their source for this is [this W3Schools article](http://www.w3schools.com/tags/ref_urlencode.asp) which doesn't provide any sources.

As far as I've been able to dig up, + and SPACE are only interchangable for `application/x-www-form-urlencoded` form requests ([WHATWG](https://url.spec.whatwg.org/#urlencoded-parsing), [W3C](https://www.w3.org/TR/html401/interact/forms.html#h-17.13.4)). 

If nothing else it seems like this behavior could/should be modifiable via a flag in the qs.parse options object.

**Comment by ljharb** [comment]
I'd certainly be open to adding a `parse` flag - that seems perfectly reasonable.

**Comment by svincent** [comment]
In that case I'll take a crack at a PR later this week. Cheers 🙂

**Comment by mvattuone** [comment]
Was there ever a PR made to account for this behavior? Running into an issue using this module, currently.

**Comment by svincent** [comment]
Sorry, no. I got busy and unfortunately it fell off my radar.

**Comment by mvattuone** [comment]
No worries!
