### ISSUE TITLE
qs.stringify converts mongo ObjectID to an object instead of a string

### ISSUE THREAD

**Issue by faboulaws** [ljharb/qs#167]
When stringify is called with a  mongodb ObjectID it turns it into something like this
`{_bsontype:'ObjectID', id:<raw bson data>}`

Is it possible to add a setting the the opts parameter to automatically call toString() on certain objects?

**Comment by ljharb** [comment]
I'm relatively confident that *is* the `toString` output of a mongo ObjectID. If you pass it into `String()`, what do you get?

**Comment by faboulaws** [comment]
Of course. There is a toString() to mongo ObjectID. 

Let clarify with examples:
When processing and object with the structure below

`var person = {user_id:<ObjectID>, username:'JohnDoe'}`

and  calling 

`qs.stringify(person)`

we get something like

`user_id[_bsontype]=ObjectID&user_id[id]=VÝU¹Bò-®Ä÷@¾&username=JohnDoe`

You can see that the user_id property is converted to an object with 2 params: **_bsontype** and **id**

What i suggest is to add a flag to the second parameter of qs.stringify, so that it uses the string value for ObjectIDs instead of treating them as regular objects.
Hope it is clear.

**Comment by ljharb** [comment]
I want to make sure I understand what the ObjectID object looks like - I'm familiar with mongoose ObjectIDs but not mongo ones. Can you share the output of the following, where `x` is the ObjectID?
 - `Object.getOwnPropertyNames(x)`
 - `String(x)`
 - `JSON.stringify(x)`
 - `Object.getPrototypeOf(x) === Object.prototype`
 - `Object.getPrototypeOf(x) === null`

Thanks!

**Comment by faboulaws** [comment]
Sorry, I actually meant mongoose ObjectID.

For an example ObjectID from mongoose we get:

- `Object.getOwnPropertyNames(x)  => [ "_bsontype",  "id"]`
- `String(x) => "54a28815636d7324f8040000"`
- `JSON.stringify(x) => "54a28815636d7324f8040000"`
- `Object.getPrototypeOf(x) => ObjectID`

Thanks

**Comment by ljharb** [comment]
You can currently do this by providing a custom `encoder` function, but you'd have to also handle all the web encoding that `qs` currently does.

It would be a pretty major breaking change to stringify rather than destructure object inputs, so I don't think that can happen. Doing it through a param could be possible, but then if your Person had an object-valued property on it, that might produce the wrong information.

I'll keep thinking on it, but I think the proper solution is that you stringify your ObjectIDs before passing objects containing them to `qs.stringify`.

**Comment by ljharb** [comment]
This seems like it should be closed for now - I think the best approach is that you manually stringify your ObjectIDs.

**Comment by jsmestad** [comment]
I would love to see support for this!
