### ISSUE TITLE
Parsing bug

### ISSUE THREAD

**Issue by BenjaminHorn** [ljharb/qs#188]
this parameter string 
`[where][and][0][valid]=true&filter[where][and][1][or][0][name]=test&filter[where][and][1][or][1][deleted]=false` 

gets parsed as:

`{"and":[{"valid":true},{"or":[{"[name]":"test"},{"[deleted]":false}]}]}`
_note the square brackets around name and deleted_

We found this behavior in [Loopback](https://github.com/strongloop/loopback), which uses this module for parsing parameters. @raymondfeng suggested to open here an issue, and kindly provided a snippet to demonstrate the problem:

```Javascript
var assert = require('assert');
var qs = require('qs');
var json = {filter: {where: {"and":[{"valid":true},{"or":[{"name":"test"},{"deleted":false}]}]}}};
var x = qs.stringify(json, { encode: false });
var y = qs.parse(x);
console.log('%j %j', json, y);
assert.deepEqual(json, y); // will throw
```

Here you can find the original [issue](https://github.com/strongloop/loopback/issues/3017),

**Comment by ljharb** [comment]
The differences I see in your example are:
 - `json.filter.where.and[0].valid === true` but `y.filter.where.and[0].value === 'true'`
 - `$.filter.where.and[1].or`:
   - `json.filter.where.and[1].or` => `[ { name: 'test' }, { deleted: false } ]`
   - `y.filter.where.and[1].or` => `[ { '[name]': 'test' }, { '[deleted]': 'false' } ]`

`qs.parse` has a default `depth` option of 5 (documented in the readme) - if you do `var y = qs.parse(x, { depth: 10 });`, for example, you'll get the following:
 - `$.filter.where.and[1].or`:
   - `json.filter.where.and[1].or` => `[ { name: 'test' }, { deleted: false } ]`
   - `y.filter.where.and[1].or` => `[ { 'name': 'test' }, { 'deleted': 'false' } ]`

which only leaves the booleans on the front end of the pipeline ending up as strings on the back end.

Parsing booleans is https://github.com/ljharb/qs/issues/91#issuecomment-234161081 - since everything that comes in via a querystring is a string, there's no safe way to automatically parse the strings "true" and "false" into booleans without breaking places with the actual string true or false. However, you can pass an explicit `decoder` option to `qs.parse` that handles this.

Note the following, with changes:
```js
var assert = require('assert');
var qs = require('qs');
var json = {filter: {where: {"and":[{"valid":true},{"or":[{"name":"test"},{"deleted":false}]}]}}};
var x = qs.stringify(json, { encode: false });
var y = qs.parse(x, { depth: 10, decoder: function (x) { if (x === 'true') { return true; } else if (x === 'false') { return false; } return x; } });
console.log('%j %j', json, y);
assert.deepEqual(json, y); // will NOT throw
```

**Comment by jackypan1989** [comment]
To extend query parser to handle 'true' / 'false' / 'null' in qs
https://github.com/jackypan1989/express-query-parser
