### ISSUE TITLE
Consider having installation section with at least the npm package name

### ISSUE THREAD

**Issue by jinalskothari** [ljharb/qs#208]
It may not be obvious to all that this lib lives in the npm registry with the same package name. It may be helpful to have a section in readme with this information. Happy to make a PR.

**Comment by ljharb** [comment]
Everything worth using lives in the npm registry, so that should be the default assumption :-)

However, I thoroughly agree that the readme should be more informative here - if you'd follow the example in https://raw.githubusercontent.com/ljharb/is-typed-array/master/README.md for the version number, the npm badge, and for funsies, the dep/dev dep badges and the license image (using the same footnote style), that'd be appreciated!

**Comment by ljharb** [comment]
@jinalskothari please let me know if you're interested in making a PR for this.

**Comment by jinalskothari** [comment]
@ljharb, I can take it up in 3 days and make PR. I'll check and post here before starting to avoid duplicated effort.

**Comment by ljharb** [comment]
@jinalskothari should i take care of this?

**Comment by jinalskothari** [comment]
Sorry I couldn't find time. @ljharb Yes please.
