### ISSUE TITLE
Make stringify object type more specific

### ISSUE THREAD

**Issue by kvendrik** [ljharb/qs#257]
I feel like the `qs.stringify` object argument TypeScript type might be a bit too forgiving. Currently its set to `any` and I was wondering if it wouldn't be better to set it to something like:

```ts
export interface QueryObject {
  [key: string]: string | number | string[] | number[] | QueryObject;
}
```

The advantage here would be that there is more clarity about what the object can contain. Users would for example get an error when they accidentally throw a function in there somehow.

The above probably doesn't account for all use cases but you get the idea. 😄

**Comment by ljharb** [comment]
qs is written in JavaScript, and has no types. You'll presumably need to file an issue on DefinitelyTyped, which is typically where type definitions are stored.

**Comment by kvendrik** [comment]
For reference: https://github.com/DefinitelyTyped/DefinitelyTyped/issues/25535

**Comment by valoricDe** [comment]
Many projects on npm nowadays include a typings.d.ts into their modules so that it just works rightaway. Don"t you think it makes sense to also do it for this project?

**Comment by ljharb** [comment]
Nope! If a project isn't written in TypeScript, there's no way in CI to force the types to stay in sync with the JS - as such, it is an *exceedingly* bad idea for any non-TypeScript project to include TypeScript types.

If such a mechanism exists, however, I'd reconsider - for qs, and for all my libraries.

**Comment by FredericLatour** [comment]
@ljharb Not sure to understand your answer. It's indeed more and more common for projects that are not written in typescript to include typescript types. Why would it be a bad idea and why would it be any different than having types in a separate package (DefinitelyTyped)?

It has many advantages from the package user point of view:
* you don't have to add a separate package in order to have typings
* You don't need to ensure to have the proper version of each package. 

The only constraint for the package author is that the types need to be updated when the package public api is changed. It does not often that much and is usually not that difficult to make any small changes starting from existing types even for a non typescript expert.

**Comment by FredericLatour** [comment]
I've just checked yargs and it looks like they are including types in the current source code. Or did I miss something?

Yes a breaking change in the types would mean a major bump. A way to mitigate this is to pass parameters as an option object and keep compatibility by using union types or optional values.
Does it anyway happens that frequently compared to the pain in the ass of having two packages that you need to keep in sync in order to get types? 
I don't know for sure, however, from my experience, more and more packages, include types definition and this is a common request.

In the meantime, I could find a package that includes types information (query-string) so that's fine by me.

**Comment by ljharb** [comment]
I don't see any in the published package: https://unpkg.com/browse/yargs@16.0.3/

Yes, it does, and the PITA is because the typescript team has failed to provide a tool to automatically manage needed DT packages. The solution isn't to force non-TS devs from having to endure TypeScript.

**Comment by FredericLatour** [comment]
Well, obviously, I'm biased. If it was not Typescript, I wouldn't even bother with Javascript in the first place and the more TS the better.
Anyway, thanks for the feedback.
