### ISSUE TITLE
post，qs.stringify传数据到后台

### ISSUE THREAD

**Issue by chengbinHuang** [ljharb/qs#271]
qs.stringify传数据到后台都会把原先的数据格式转成字符串，比如原来是number类型的就会转成字符串的。如果不想改变原来的数据类型，而且也是采用Form Data的传递方式，怎么处理？

**Comment by ljharb** [comment]
[google translate](https://translate.google.com/m/translate#auto/en/qs.stringify传数据到后台都会把原先的数据格式转成字符串，比如原来是number类型的就会转成字符串的%E3%80%82如果不想改变原来的数据类型，而且也是采用Form%20Data的传递方式，怎么处理？) says:
> qs.stringify will pass the data to the background and convert the original data format into a string. For example, if it is a number type, it will be converted into a string. If you don't want to change the original data type, but also use the Form Data transfer method, how to deal with it?

If you’re using FormData, then I’m not sure why you’d be using a query string library at all - since you won’t be using query strings. Can you elaborate on your use case?

**Comment by chengbinHuang** [comment]
I see. Thank you

**Comment by ljharb** [comment]
I'm going to close this, but am happy to reopen it if needed.
