### ISSUE TITLE
Parsing error， the plus sign is replaced by a blank space.    + place space

### ISSUE THREAD

**Issue by xiaoyongchen** [ljharb/qs#277]
const url = "?sign=T5E2Dx1z01QDCs+UryhQ/DhQ5gyaJUoSa8PQ==";
const params = qs.parse(url);
const value = params.sign;   
=> value == T5E2Dx1z01QDCs  UryhQ/DhQ5gyaJUoSa8PQ==

The result is wrong.

**Comment by ljharb** [comment]
Why is that wrong?

**Comment by ljharb** [comment]
You may want to read this: https://github.com/ljharb/qs#rfc-3986-and-rfc-1738-space-encoding

**Comment by olivoil** [comment]
Thanks for pointing out to the docs @ljharb. It's not clear to me from the doc if and how one could opt in to keep special characters such as "+" intact when decoding a query string. Maybe it's worth improving the doc to make it more explicit?

**Comment by ljharb** [comment]
@olivoil that link shows you the recommended way to do it; i'm not sure how to make the docs any more clear.

**Comment by olivoil** [comment]
@ljharb thinking of something very simple like adding this at the end of the section you linked to:

> In order to encode or decode characters differently from these specifications, supply a custom `decoder` or `encoder` option, as detailed above. This may be useful to keep characters that would otherwise be encoded as spaces intact, such as '+' or '%20'.

If you think this is useful, I'm happy to send a PR

**Comment by ljharb** [comment]
@olivoil i'm confused; the readme suggests using the appropriate format, rather than making one-off overrides via an encoder/decoder. When would you want to use RFC1738 encoding of "+" without using the RFC1738 format?

**Comment by olivoil** [comment]
Hey, sorry about the confusion. I don't want to use any particular RFC encoding, I just tried it because you pointed to it... The only thing I'm trying to do is to decode a query string value that contains a `+` sign in it, and not have it decoded as a space character. I tried specifying both formats from the section you pointed out to, but both decoded '+' as a space... 

```
> qs.parse("val=lsakdjfslkdfj+lskdjfsldkfj")
{ val: 'lsakdjfslkdfj lskdjfsldkfj' }
> qs.parse("val=lsakdjfslkdfj+lskdjfsldkfj", {format: "RFC3986"})
{ val: 'lsakdjfslkdfj lskdjfsldkfj' }
> qs.parse("val=lsakdjfslkdfj+lskdjfsldkfj", {format: "RFC1739"})
{ val: 'lsakdjfslkdfj lskdjfsldkfj' }
```

So I searched for another solution in the docs and found the `decoder` option could do what I needed to.

```
> qs.parse("val=lsakdjfslkdfj+lskdjfsldkfj", {decoder: (c) => c})
{ val: 'lsakdjfslkdfj+lskdjfsldkfj' }
```

The whole thing lead me to let you know I'm not sure what the recommended solution is based on the docs.  The `format` option you pointed out to didn't seem to help. Is there a better way to parse a query string and preserve `+` than using a `decoder` option?

If the docs already point it out explicitly and I'm just not seeing it, my bad. If not, there's probably a way to improve it so others don't make the same mistake.

**Comment by ljharb** [comment]
No, there's no better way to do it but the `decoder` option.

However, the thing that's wrong here isn't that the `+` gets turned into a space it's that a query string of `?sign=T5E2Dx1z01QDCs+UryhQ/DhQ5gyaJUoSa8PQ==` is invalid in the first place, because the plus sign is special in a query string. You should be starting with `?sign=T5E2Dx1z01QDCs%2BUryhQ/DhQ5gyaJUoSa8PQ==` (ie, passing the `sign` value into `encodeURIComponent` first).

**Comment by olivoil** [comment]
I don't have control over how the urls I need to parse are encoded unfortunately. Using a `decoder` works for my use case though, it has the flexibility I need to process these values. Thanks for the help!

**Comment by SachaG** [comment]
I just ran into the same issue and I similarly don't have control over the URLs that need to be parsed, so @olivoil's fix was helpful. I think it'd be worth expanding on this issue in the docs, and make it clearer how to deal with specific characters without necessarily affecting the encoding itself.

**Comment by ljharb** [comment]
Sure, PRs to improve docs are always welcome.

**Comment by CommanderXL** [comment]
@olivoil Well, in my opinion.If someone to give your some params which contain the special string in the url, they should encode first.
