### ISSUE TITLE
Throw error when parameterLimit is crossed

### ISSUE THREAD

**Issue by eliseumds** [ljharb/qs#376]
First of all, thanks for the work you people put in this library. I've been using it for years in every project.

I understand the idea behind limiting the amount of parameters to be parsed, after all, URLs with query strings are very rarely too long. However, when we use `Content-Type: application/x-www-form-urlencoded`, the request is a query string and basically unlimited. In any case, I believe that the correct behaviour would be to throw an exception when *parameterLimit* is crossed to avoid broken data. For example:

```
...tonsOfData...&customer[name]=Demo&customer[emailAddress]=demo@gmail.com
```

Boom, the customer data is lost, or, even worse, it might be parsed half-way through only.

Ideally it'd be unlimited by default, since tools like nginx already limit the URL length anyway. Same with *arrayLimit*.

**Comment by ljharb** [comment]
It would be a massive security issue if it were unlimited by default - see #296 - and you can manually pass `Infinity` as an arrayLimit if you like.

I'm not sure how we could throw in the case you're talking about, because it's not a "counter" - it's just a check if the index is a number within the limit. If we threw whenever a viable array index was above the limit, then we'd break a ton of totally valid use cases where object keys happen to be numeric.
