### ISSUE TITLE
allowSparse is missing, despite being added 2 years ago?

### ISSUE THREAD

**Issue by ghengeveld** [ljharb/qs#396]
The `allowSparse` option was added to master in b04febd9cb1c94b466aa2bd81b6452b44712414e and is documented. However it isn't present in the released bundle. What happened to this option?

**Comment by ljharb** [comment]
The commit was authored in May 2019. If you click on that commit link, however, you'll see that it's not included in any release tags, and if you clicked on the linked PR (#312) you'll see it was merged one month ago, and is still unreleased.

For checking docs on *any* github project, you'll always have to switch to the appropriate released tag, instead of looking at the default branch.

**Comment by ghengeveld** [comment]
Right. My typical assumption is that `master` is what's actually released, and a `next` or `dev` branch is what contains the ongoing state of development. Thanks for explaining though.

**Comment by ljharb** [comment]
That assumption does not hold for any GitHub repo I’ve ever seen or used.

**Comment by yannbf** [comment]
Hey @ljharb thanks a lot for this library! Is there a place to get any info about upcoming releases? I'm wondering if this feature will be part of a major or minor release.

**Comment by ljharb** [comment]
New features would be semver-minor.

Upcoming releases are unplanned, so there’s no info until a release happens.
