### ISSUE TITLE
Lately involved side-channel makes the whole lib not working.

### ISSUE THREAD

**Issue by wanglijie** [ljharb/qs#401]
![image](https://user-images.githubusercontent.com/3660583/111880103-61207d00-89e4-11eb-971a-8c08b5a01133.png)

Pls double check this. It cannot work through this line.

**Comment by ljharb** [comment]
I'm not sure what you mean - the library works fine. Your screenshot doesn't make it clear what the problem is; it just shows two breakpoints.

If you're using webpack 5, however, you may not be aware that it's [broken by default](https://blog.sindresorhus.com/webpack-5-headache-b6ac24973bf1) - you'll need to fix it to polyfill node globals so that it's a working node module bundler.

In other words, I'm assuming this is related to https://github.com/inspect-js/has-symbols/issues/11, which is actually solved in the latest version of `has-symbols` (make sure your lockfile is properly updated).
