### ISSUE TITLE
rename option `filter` to `filterMap`

### ISSUE THREAD

**Issue by gomain** [ljharb/qs#448]
Because that's what it is. See https://github.com/ljharb/qs/issues/446#issuecomment-1183165378

**Comment by ljharb** [comment]
There’s nowhere near enough value in the rename to be worth the churn of changing it.

**Comment by ljharb** [comment]
I agree that what the option does, in an FP world, would be named "filterMap".

Breaking changes are very costly, so dropping use of the name "filter" is *not* worth it. Adding "filterMap" and deprecating "filter" would avoid this problem, but it would then create confusion - since both would need to be documented.

The "filter" option was added in #81, over 7 years ago. Since then, out of the 67 million people downloading it a week (these aren't likely unique, so it would be incorrect to extrapolate that to 24 billion), you are the only person that has ever raised the question of the naming of this option.

So, certainly if it was based on demand, it would be an immediate no. Basing it on principle, while I agree that perhaps "filterMap" would have been a better initial name, now that "filter" is established, I think that the principles of minimizing churn and confusion and breakage far outweigh the academic principle of FP correctness. Not everything needs to be a monad or a functor.
