### ISSUE TITLE
Option to omit array indices

### ISSUE THREAD

**Issue by ryanseys** [ljharb/qs#46]
I would like to have the option to omit array indices from the stringify. That is:

``` js
qs.stringify({ a: ['b', 'c'] }, { indices: false }); // should return a=b&a=c
```

This is important for formatting requests that are compatible with the Google APIs which don't accept array indices in their request query parameters.

**Comment by Dakuan** [comment]
Trouble with this is that if you are dealing with a PHP or Rails backend, it expects

`a[]=b&a[]=c`

**Comment by wvengen** [comment]
The presence of an index is an issue [here](https://github.com/rendrjs/rendr/issues/416) as well. What about omitting indices when the option `indices` is set to `'empty'`?

**Comment by Dakuan** [comment]
I know we dont like breaking changes, but I wonder if the *ideal* solution takes account of the fact that there are 3 array formats in use:

Rails, PHP, jQuery: `a[]=b&a[]=c`
Java, Go, c#: `a=b&a=c`
Express: `a[0]=b&a[1]=b`

something along the lines of:

``` javascript
qs.stringify({ a: ['b', 'c'] }, { format: 'brackets' }); //a[]=b&a[]=c
qs.stringify({ a: ['b', 'c'] }, { format: 'repeat' }); //a=b&a=c
qs.stringify({ a: ['b', 'c'] }, { format: 'indices' }); //a[0]=b&a[1]=c
```

**Comment by Dakuan** [comment]
@wvengen see https://github.com/hapijs/qs/pull/65 too

**Comment by nlf** [comment]
I think that's a good compromise

**Comment by wvengen** [comment]
Thanks, @Dakuan, for making it clear that the three array formats are all used.

I'm seeing four proposals:
1. Don't remove brackets when `indices` is `false` - #65
2. New option `brackets` in addition to `indices` - https://github.com/hapijs/qs/pull/65#issuecomment-69627429
3. New option `format` to replace `brackets` - https://github.com/hapijs/qs/issues/46#issuecomment-69898182
4. New value `empty` for `indices` - https://github.com/hapijs/qs/issues/46#issuecomment-69897630

The first breaks backwards compatibility, so that doesn't have my preference. Two seems more verbose (two variables to set for one issue: how to serialize arrays). Three would include deprecation of the `indices` parameter in favour of `format` but is otherwise very clear. Four would be easiest, but it might be slightly confusing to accept both booleans as strings as values.

I'd like to propose a number five
5. Use string values for `indices` (like `brackets`, `repeat`, `indices`), while allowing `true` and `false` to remain backward-compatible (optionally deprecating them at the next major release).

**Comment by Dakuan** [comment]
@wvengen I think thats a bit confusing, the word indices looses its meaning - `{indices: 'brackets'}` wouldn't really explain whats going on if you were coming at the code cold. How about:

``` javascript
var q = {
   a: ['b', 'c']
};

// don't break current default
qs.stringify(q) //a[0]=b&a[1]=c 

// deprecate indices option, but just warn for now to not break
qs.stringify(q, {indices: false} // //a=b&a=c DEPRECATION WARNING, please use {format: 'repeat'} 

// new format option, its semantic and can be expanded if the next hot framework
// takes a new approach
qs.stringify(q, { format: 'brackets' }); //a[]=b&a[]=c
qs.stringify(q, { format: 'repeat' }); //a=b&a=c
qs.stringify(q, { format: 'indices' }); //a[0]=b&a[1]=c
```

**Comment by wvengen** [comment]
@Dakuan Hmm I agree :) Then, reading your example, I'm wondering if 'arrayFormat' or 'arrays' would be clearer? These options are for the whole stringification, and this only handles about arrays.

**Comment by Dakuan** [comment]
true! I like `arrayFormat`

@nlf thoughts?

**Comment by nlf** [comment]
I'm a +1 for arrayFormat
